name: The Peoples Country Web Deployment

on:
  push:
    branches:
      - main
      - feat/hosting-digitalocean

# DIGITALOCEAN_ACTION: https://github.com/marketplace/actions/digitalocean-app-platform-deployment

jobs:
  deploy-to-digitalocean:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github object: '${{ toJson(github) }}'"
          echo "runner object: '${{ toJson(runner) }}'"
          echo "job object: '${{ toJson(job) }}'"
      - name: Check Repository Code
        uses: actions/checkout@v4
      # - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      - name: Build Nuxt Project
        run: |
          cd ${{ github.workspace }}/src
          yarn install
          yarn build
      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy to DigitalOcean
        run: |
          cd ${{ github.workspace }}
          doctl apps create --spec .do/app.yaml --upsert
      # - name: List files in the repository
      #   run: |
      #     cd ${{ github.workspace }}
      #     doctl apps create --spec .do/app.yaml --upsert
      # - name: DigitalOcean App Platform deployment
      #   uses: digitalocean/app_action@v1.1.6
      #   with:
      #     app_name: the-peoples-country
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: echo "🍏 This job's status is ${{ job.status }}."